/**
 * KKEEY IT-Profil — Inhaltsdatei v3.5
 * Future Orchestrator Interface — KKEEY Liquid Glass (Orange / Azure)
 * Multilingual: DE / EN / FR / UK / PL
 * E-Mails: hello@kkeey.dev · office@kkeey.dev
 */
window.KKIT_DATA = {

  // ─── HERO & TYPED ROLES ─────────────────────────────────────────────────────
  hero: {
    greeting: {
      de: 'System Interface · Future Orchestrator',
      en: 'System Interface · Future Orchestrator',
      fr: 'Interface Système · Orchestrateur Futur',
      uk: 'Системний Інтерфейс · Future Orchestrator',
      pl: 'Interfejs Systemowy · Future Orchestrator',
    },
    name: 'Kevin Kuck',
    roles: {
      de: [
        'IT-Administrator · Systemadministration',
        'Identity & Access Management (AD · Entra ID)',
        'KRITIS-Infrastruktur & Endpoint Governance',
        'PowerShell- & Workflow-Orchestrierung',
        'Enterprise Support & Prozessautomatisierung',
      ],
      en: [
        'IT Administrator · System Administration',
        'Identity & Access Management (AD · Entra ID)',
        'Critical Infrastructure & Endpoint Governance',
        'PowerShell & Workflow Orchestration',
        'Enterprise Support & Process Automation',
      ],
      fr: [
        'Administrateur IT · Gestion des Systèmes',
        'Gestion des Identités et Accès (AD · Entra ID)',
        'Infrastructures Critiques & Sécurité des Endpoints',
        'Orchestration des Workflows & PowerShell',
        'Support Entreprise & Automatisation des Processus',
      ],
      uk: [
        'IT-Адміністратор · Системне адміністрування',
        'Керування ідентифікацією та доступом (AD · Entra ID)',
        'Критична інфраструктура (KRITIS) & Endpoint Governance',
        'PowerShell & Оркестрація робочих процесів',
        'Enterprise Підтримка & Автоматизація процесів',
      ],
      pl: [
        'Administrator IT · Administracja Systemami',
        'Identity & Access Management (AD · Entra ID)',
        'Infrastruktura Krytyczna (KRITIS) & Endpoint Governance',
        'PowerShell & Orkiestracja Przepływów Pracy',
        'Enterprise Support & Automatyzacja Procesów',
      ],
    },
    meta: {
      de: '15+ Jahre Berufspraxis · IT-Systemadministration · Butzbach · Remote / Hybrid',
      en: '15+ years of professional practice · IT System Administration · Butzbach, Germany · Remote / Hybrid',
      fr: '15 ans d\'expérience IT · Infrastructures critiques · Butzbach · Distanciel / Hybride',
      uk: '15+ років професійної практики · Досвід роботи з KRITIS · Буцбах · Remote / Hybrid',
      pl: '15+ lat praktyki zawodowej · Doświadczenie w KRITIS · Butzbach · Remote / Hybrydowo',
    },
    cta1: { de: 'IT-Portfolio ansehen', en: 'View IT Portfolio', fr: 'Voir le portfolio IT', uk: 'Переглянути IT-портфоліо', pl: 'Zobacz Portfolio IT' },
    cta2: { de: 'Bewerbungsmappe (PDF)', en: 'Download CV (PDF)', fr: 'Dossier de candidature (PDF)', uk: 'Резюме / Портфоліо (PDF)', pl: 'Pobierz CV (PDF)' },
    cta3: { de: 'Kontakt aufnehmen', en: 'Get in touch', fr: 'Me contacter', uk: 'Зв\'язатися', pl: 'Skontaktuj się' },
    available: {
      de: 'Offen für berufliche Möglichkeiten',
      en: 'Open to professional opportunities',
      fr: 'Ouvert aux opportunités professionnelles',
      uk: 'Відкритий до професійних можливостей',
      pl: 'Otwarty na możliwości zawodowe',
    },
    caps: {
      de: ['Infrastruktur', 'Automatisierung', 'Compliance', 'Security', 'Monitoring', 'IAM'],
      en: ['Infrastructure', 'Automation', 'Compliance', 'Security', 'Monitoring', 'IAM'],
      fr: ['Infrastructure', 'Automatisation', 'Conformité', 'Sécurité', 'Monitoring', 'IAM'],
      uk: ['Інфраструктура', 'Автоматизація', 'Відповідність', 'Безпека', 'Моніторинг', 'IAM'],
      pl: ['Infrastruktura', 'Automatyzacja', 'Zgodność', 'Bezpieczeństwo', 'Monitoring', 'IAM'],
    },
  },

  // ─── ENTERPRISE OVERVIEW ────────────────────────────────────────────────────
  overview: {
    label: { de: 'Enterprise IT', en: 'Enterprise IT', fr: 'IT d\'Entreprise', uk: 'Enterprise IT', pl: 'Enterprise IT' },
    title: {
      de: 'Sechs Domänen. Eine Verantwortung.',
      en: 'Six Domains. One Responsibility.',
      fr: 'Six Domaines. Une Responsabilité.',
      uk: 'Шість Доменів. Одна Відповідальність.',
      pl: 'Sześć Domen. Jedna Odpowiedzialność.',
    },
    sub: {
      de: 'Orchestrierung komplexer IT-Umgebungen über alle Schichten — von der Identität bis zur Governance.',
      en: 'Orchestrating complex IT environments across all layers — from identity to governance.',
      fr: 'Orchestration d\'environnements informatiques complexes à tous les niveaux — de l\'identité à la gouvernance.',
      uk: 'Оркестрація комплексних IT-середовищ на всіх рівнях — від ідентифікації до управління.',
      pl: 'Orkiestracja złożonych środowisk IT na wszystkich poziomach — od tożsamości po zarządzanie.',
    },
    domains: [
      {
        icon: 'cloud',
        title: { de: 'Cloud-Grundlagen', en: 'Cloud Basics', fr: 'Cloud & Hybride', uk: 'Cloud & Hybrid', pl: 'Cloud & Hybryda' },
        sub: { de: 'Microsoft Azure · Kursnachweise', en: 'Microsoft Azure · Certificates', fr: 'Microsoft Azure · Entra ID', uk: 'Microsoft Azure · Entra ID', pl: 'Microsoft Azure · Entra ID' },
        desc: {
          de: 'Azure- und Identity-Grundlagen aus Kursnachweisen (AZ-900, Entra ID Grundkurs), angewendet in eigenen Projekten mit Docker und Google Cloud Run.',
          en: 'Azure and Identity basics from certificates (AZ-900, Entra ID basic course), applied in personal projects with Docker and Google Cloud Run.',
          fr: 'Synchronisation Azure AD, administration Entra ID, jonction hybride et stratégies d\'accès conditionnel.',
          uk: 'Синхронізація Azure AD, адміністрування Entra ID, Hybrid-Join, політики Conditional Access для KRITIS.',
          pl: 'Synchronizacja Azure AD, administracja Entra ID, Hybrid Join, zasady dostępu warunkowego dla środowisk KRITIS.',
        },
      },
      {
        icon: 'server',
        title: { de: 'On-Prem Infrastructure', en: 'On-Prem Infrastructure', fr: 'Infrastructure Sur Site', uk: 'On-Prem Інфраструктура', pl: 'Infrastruktura On-Prem' },
        sub: { de: 'Active Directory · Windows Server', en: 'Active Directory · Windows Server', fr: 'Active Directory · Windows Server', uk: 'Active Directory · Windows Server', pl: 'Active Directory · Windows Server' },
        desc: {
          de: 'Benutzer- und Gruppenverwaltung im Active Directory, Windows-11-Rollout mit Deskcenter Studio für rund 200 Endpoints. Laut Arbeitszeugnis: Gruppenrichtlinien und Kerberos-Authentifizierung.',
          en: 'User and group management in Active Directory, Windows 11 rollout with Deskcenter Studio for around 200 endpoints. According to reference: Group Policies and Kerberos authentication.',
          fr: 'Administration Active Directory, GPO, déploiement de Windows 11 via Deskcenter Studio pour rund 90.000 objets.',
          uk: 'Адміністрування Active Directory, керування GPO, розгортання Windows 11 через Deskcenter Studio для rund 90.000 об\'єктів.',
          pl: 'Administracja Active Directory, zarządzanie GPO, wdrażanie Windows 11 przez Deskcenter Studio dla rund 90.000 obiektów.',
        },
      },
      {
        icon: 'zap',
        title: { de: 'Automation', en: 'Automation', fr: 'Automatisation', uk: 'Автоматизація', pl: 'Automatyzacja' },
        sub: { de: 'PowerShell · Python · Workflows', en: 'PowerShell · Python · Workflows', fr: 'PowerShell · Python · Workflows', uk: 'PowerShell · Python · Workflows', pl: 'PowerShell · Python · Workflows' },
        desc: {
          de: 'Eigenentwickelte Automatisierungstools — u.a. Ticket-Routing-System im Team-Einsatz, Migrationsskripte, Provisioning-Workflows.',
          en: 'Custom automation tools — incl. ticket routing system used in production, migration scripts, provisioning workflows.',
          fr: 'Outils d\'automatisation personnalisés — système de routage de tickets en production, scripts de migration.',
          uk: 'Власні інструменти автоматизації — система маршрутизації тікетів у продакшні, міграційні скрипти, робочі процеси.',
          pl: 'Autorskie narzędzia automatyzacji — m.in. system routingu zgłoszeń w produkcji, skrypty migracyjne, procesy provisioningowe.',
        },
      },
      {
        icon: 'shield',
        title: { de: 'Security & Endpoint', en: 'Security & Endpoint', fr: 'Sécurité & Endpoints', uk: 'Безпека & Endpoints', pl: 'Bezpieczeństwo & Endpoint' },
        sub: { de: 'FortiClient · Sophos', en: 'FortiClient · Sophos', fr: 'FortiClient · Sophos · KRITIS', uk: 'FortiClient · Sophos · KRITIS', pl: 'FortiClient · Sophos · KRITIS' },
        desc: {
          de: 'Endpoint-Security mit FortiClient und Sophos, Bearbeitung von Phishing- und Spam-Meldungen. In einem KRITIS-relevanten Umfeld.',
          en: 'Endpoint security with FortiClient and Sophos, processing of phishing and spam reports. In a KRITIS-relevant environment.',
          fr: 'Sécurité des endpoints en infrastructure critique, administration FortiClient/Sophos, conformité sécuritaire.',
          uk: 'Безпека кінцевих пристроїв у критичній інфраструктурі, адміністрування FortiClient/Sophos для rund 90.000 об\'єктів.',
          pl: 'Bezpieczeństwo endpointów w infrastrukturze krytycznej, administracja FortiClient/Sophos, zgodna z normami konfiguracja.',
        },
      },
      {
        icon: 'activity',
        title: { de: 'Monitoring & Operations', en: 'Monitoring & Operations', fr: 'Supervision & Exploitation', uk: 'Моніторинг & Операції', pl: 'Monitoring & Operacje' },
        sub: { de: 'Omnitracker · Innovaphone · PBX', en: 'Omnitracker · Innovaphone · PBX', fr: 'Omnitracker · Innovaphone · PBX', uk: 'Omnitracker · Innovaphone · PBX', pl: 'Omnitracker · Innovaphone · PBX' },
        desc: {
          de: 'Ticketbasierter Support-Betrieb in Omnitracker: 553 Tickets und 366 Stunden in knapp fünf Monaten.',
          en: 'Ticket-based support operations in Omnitracker: 553 tickets and 366 hours in just under five months.',
          fr: 'Exploitation et résolution d\'incidents en environnement critique, gestion des tickets, administration PBX.',
          uk: 'IT-операції та усунення інцидентів у KRITIS-середовищі, підтримка за тікетами, адміністрування PBX.',
          pl: 'Operacje IT i usuwanie awarii w środowisku KRITIS, wsparcie oparte na ticketach, administracja PBX i nadzór systemów.',
        },
      },
      {
        icon: 'layout',
        title: { de: 'Governance & IAM', en: 'Governance & IAM', fr: 'Gouvernance & IAM', uk: 'Governance & IAM', pl: 'Governance & IAM' },
        sub: { de: 'IAM · RBAC · Compliance', en: 'IAM · RBAC · Compliance', fr: 'IAM · RBAC · Conformité', uk: 'IAM · RBAC · Відповідність', pl: 'IAM · RBAC · Zgodność' },
        desc: {
          de: 'Benutzer- und Berechtigungsverwaltung nach Rollen, Rechte für Fachanwendungen, Lizenzsteuerung über AD-Gruppen.',
          en: 'Role-based user and permission management, rights for specialized applications, license control via AD groups.',
          fr: 'Gestion des utilisateurs et des permissions, structuration RBAC, exigences de conformité dans des secteurs régulés.',
          uk: 'Керування користувачами та правами, структура RBAC, дотримання вимог комплаєнсу в регульованих середовищах.',
          pl: 'Zarządzanie użytkownikami i uprawnieniami, strukturyzacja RBAC, spełnianie wymogów regulacyjnych w sektorach krytycznych.',
        },
      },
    ],
  },

  // ─── SYSTEMS & ARCHITECTURE ─────────────────────────────────────────────────
  systems: {
    label: { de: 'Architektur', en: 'Architecture', fr: 'Architecture', uk: 'Архітектура', pl: 'Architektura' },
    title: { de: 'Stack & Systemlandschaft', en: 'Stack & System Landscape', fr: 'Stack & Paysage Système', uk: 'Стек & Системний ландшафт', pl: 'Stos Technologiczny & Środowisko' },
    sub: {
      de: 'Erprobte Enterprise-Umgebungen unter realem Produktionsdruck.',
      en: 'Battle-tested enterprise environments under real production pressure.',
      fr: 'Environnements d\'entreprise éprouvés sous pression opérationnelle.',
      uk: 'Перевірені корпоративні середовища під реальним навантаженням.',
      pl: 'Sprawdzone środowiska enterprise pod realną presją produkcyjną.',
    },
    tiers: [
      { label: { de: 'Identity', en: 'Identity', fr: 'Identité', uk: 'Identity', pl: 'Identity' }, tech: 'Active Directory', detail: { de: 'Core IAM Layer', en: 'Core IAM Layer', fr: 'Couche IAM Principale', uk: 'Базовий шар IAM', pl: 'Główna Warstwa IAM' } },
      { label: { de: 'Clients', en: 'Clients', fr: 'Clients', uk: 'Clients', pl: 'Clients' }, tech: 'Windows 11 · Deskcenter Studio · Citrix', detail: { de: 'Endpoint Management', en: 'Endpoint Management', fr: 'Gestion des Postes', uk: 'Керування кінцевими пристроями', pl: 'Zarządzanie Punktami Końcowymi' } },
      { label: { de: 'Security', en: 'Security', fr: 'Sécurité', uk: 'Security', pl: 'Security' }, tech: 'FortiClient · Sophos', detail: { de: 'Perimeter & Endpoint', en: 'Perimeter & Endpoint', fr: 'Périmètre & Sécurité', uk: 'Периметр і кінцеві точки', pl: 'Obwód & Endpoint' } },
      { label: { de: 'Automation', en: 'Automation', fr: 'Automatisation', uk: 'Automation', pl: 'Automation' }, tech: 'PowerShell · Python · REST APIs', detail: { de: 'Orchestration Layer', en: 'Orchestration Layer', fr: 'Couche d\'Orchestration', uk: 'Шар оркестрації', pl: 'Warstwa Orkiestracji' } },
      { label: { de: 'Operations', en: 'Operations', fr: 'Opérations', uk: 'Operations', pl: 'Operations' }, tech: 'Omnitracker · Innovaphone PBX', detail: { de: 'ITSM & Comms', en: 'ITSM & Comms', fr: 'ITSM & Téléphonie', uk: 'ITSM & Зв\'язок', pl: 'ITSM & Telefonia' } },
    ],
    cards: [
      {
        title: { de: 'Johanniter Bundes-IT-Services', en: 'Johanniter Bundes-IT-Services', fr: 'Infrastructure Critique chez JoBITS', uk: 'Критична інфраструктура в JoBITS', pl: 'Infrastruktura Krytyczna w JoBITS' },
        desc: {
          de: 'Bundesweite AD-Umgebung mit rund rund 90.000 Objekten. Benutzerverwaltung, Citrix-Support und Windows-11-Migration für 12 Organisationseinheiten.',
          en: 'Nationwide AD environment with around 90,000 objects. User management, Citrix support and Windows 11 migration for 12 organizational units.',
          fr: 'Gestion nationale de rund 90.000 objets AD chez Johanniter Bundes-IT-Services. Environnement Citrix, Hybrid Azure AD Join, migration Windows 11, sécurité FortiClient/Sophos.',
          uk: 'Всенімецьке адміністрування rund 90.000 AD-об\'єктів у Johanniter Bundes-IT-Services. Citrix, Hybrid Azure AD Join, міграція Windows 11, FortiClient/Sophos.',
          pl: 'Ogólnokrajowe zarządzanie rund 90.000 obiektami AD i kontami w Johanniter Bundes-IT-Services. Środowisko Citrix, Hybrid Azure AD Join, migracja Windows 11, bezpieczeństwo FortiClient/Sophos.',
        },
        tags: ['Active Directory', 'Citrix', 'Windows 11', 'KRITIS-Umfeld'],
      },
      {
        title: { de: 'BAUHAUS (14 Jahre)', en: 'BAUHAUS (14 years)', fr: 'BAUHAUS IT (14 ans de pratique)', uk: 'BAUHAUS IT (14 років практики)', pl: 'BAUHAUS IT (14 Lat Praktyki)' },
        desc: {
          de: 'Warenwirtschaft, Inventory Management und Prozessoptimierung im laufenden Handelsbetrieb. Direkte Kenntnis der Anwenderseite aus dem Produktivbetrieb.',
          en: 'Merchandise management, inventory management and process optimization in ongoing retail operations. Direct knowledge of the user side from production.',
          fr: 'Responsabilité technique des systèmes ERP, du matériel et de l\'infrastructure en milieu commercial. Support Niveaux 1 à 3 avec maîtrise opérationnelle.',
          uk: 'Технічна відповідальність за системи товарообігу, обладнання та IT-інфраструктуру. Підтримка 1-3 рівнів із глибоким розумінням щоденних процесів.',
          pl: 'Odpowiedzialność techniczna za systemy ERP, sprzęt i infrastrukturę IT w handlu. Wsparcie L1-L3 z bezpośrednią znajomością realiów użytkowników.',
        },
        tags: ['Warenwirtschaft', 'Hardware', 'Prozessoptimierung'],
      },
    ],
  },

  // ─── AUTOMATION & AGENTS ────────────────────────────────────────────────────
  automation: {
    label: { de: 'Automation', en: 'Automation', fr: 'Automatisation', uk: 'Автоматизація', pl: 'Automatyzacja' },
    title: { de: 'Orchestrierung & Automatisierung', en: 'Orchestration & Automation', fr: 'Orchestration & Automatisation', uk: 'Оркестрація & Автоматизація', pl: 'Orkiestracja & Automatyzacja' },
    sub: {
      de: 'Systeme, die Prozesse selbstständig und fehlerfrei steuern — nicht nur Skripte ausführen.',
      en: 'Systems that steer processes autonomously and fault-tolerantly — not just running isolated scripts.',
      fr: 'Des systèmes qui orchestrent les processus de façon autonome et robuste.',
      uk: 'Системи, які автономно та безпомилково керують процесами, а не просто виконують скрипти.',
      pl: 'Systemy, które autonomicznie i bezbłędnie sterują procesami — a nie tylko wykonują skrypty.',
    },
    pipeline: [
      { num: '01', title: { de: 'Ereignis-Trigger', en: 'Event Trigger', fr: 'Déclencheur d\'Événement', uk: 'Тригер події', pl: 'Wyzwalacz Zdarzenia' }, desc: { de: 'Neue Tickets, AD-Änderungen, Alerts oder Zeitplan-Auslöser', en: 'New tickets, AD changes, alerts or scheduled triggers', fr: 'Nouveaux tickets, modifications AD, alertes ou planificateurs', uk: 'Нові тікети, зміни в AD, алерти або розклад', pl: 'Nowe zgłoszenia, zmiany w AD, alerty lub harmonogramy' }, status: 'done' },
      { num: '02', title: { de: 'Klassifikation', en: 'Classification', fr: 'Classification', uk: 'Класифікація', pl: 'Klasyfikacja' }, desc: { de: 'Regelbasierte Kategorisierung und Prioritätszuweisung', en: 'Rule-based categorization and priority assignment', fr: 'Catégorisation basée sur des règles et priorité', uk: 'Категоризація на основі правил і пріоритезація', pl: 'Kategoryzacja oparta na regułach i przypisywanie priorytetów' }, status: 'done' },
      { num: '03', title: { de: 'Routing & Zuweisung', en: 'Routing & Assignment', fr: 'Routage & Assignation', uk: 'Маршрутизація & Призначення', pl: 'Routing & Przypisanie' }, desc: { de: 'Automatische Zuweisung an den richtigen Bearbeiter (Ticket-Tool im Team-Einsatz)', en: 'Automatic assignment to the right agent (ticket tool used in production)', fr: 'Attribution automatique à l\'agent compétent (outil en production)', uk: 'Автоматичне призначення відповідального (інструмент у продакшні)', pl: 'Automatyczne przypisanie do odpowiedniego agenta (narzędzie w produkcji)' }, status: 'running', active: true },
      { num: '04', title: { de: 'Ausführung', en: 'Execution', fr: 'Exécution', uk: 'Виконання', pl: 'Wykonanie' }, desc: { de: 'PowerShell / Python / REST-API-Calls für Provisionierung, Migration oder Konfiguration', en: 'PowerShell / Python / REST API calls for provisioning, migration or configuration', fr: 'Appels PowerShell / Python / REST API pour provisioning ou migration', uk: 'PowerShell / Python / REST API для провіженінгу, міграції або налаштування', pl: 'PowerShell / Python / REST API do provisioningu, migracji lub konfiguracji' }, status: 'queued' },
      { num: '05', title: { de: 'Audit & Logging', en: 'Audit & Logging', fr: 'Audit & Journalisation', uk: 'Аудит & Логування', pl: 'Audyt & Logowanie' }, desc: { de: 'Nachvollziehbare Protokollierung aller Aktionen für Compliance und Review', en: 'Traceable logging of all actions for compliance and review', fr: 'Journalisation complète pour la conformité et les audits', uk: 'Прозоре документування всіх дій для комплаєнсу та аудиту', pl: 'Przejrzyste rejestrowanie wszystkich działań na potrzeby compliance i audytów' }, status: 'queued' },
    ],
    agents: [
      { icon: '⚡', name: { de: 'Ticket-Router', en: 'Ticket Router', fr: 'Routeur de Tickets', uk: 'Ticket Router', pl: 'Router Zgłoszeń' }, desc: { de: 'Regelbasierte Zuweisung für Support-Tickets im Team', en: 'Rule-based ticket assignment for support teams', fr: 'Attribution intelligente des tickets de support', uk: 'Маршрутизація тікетів підтримки на основі правил', pl: 'Automatyczne przypisywanie ticketów wsparcia w zespole' } },
      { icon: '🔐', name: { de: 'IAM-Provisioner', en: 'IAM Provisioner', fr: 'Provisionneur IAM', uk: 'IAM Provisioner', pl: 'IAM Provisioner' }, desc: { de: 'AD/Entra ID Benutzer-Lifecycle Automation', en: 'AD/Entra ID user lifecycle automation', fr: 'Automatisation du cycle de vie des comptes AD/Entra ID', uk: 'Автоматизація життєвого циклу користувачів AD/Entra ID', pl: 'Automatyzacja cyklu życia kont AD/Entra ID' } },
      { icon: '🔄', name: 'KKI Agent Framework', desc: { de: 'Wiederverwendbare Bausteine für Workflow-Automatisierung', en: 'Reusable building blocks for workflow automation', fr: 'Composants réutilisables pour l\'automatisation de workflows', uk: 'Багаторазові модулі для автоматизації робочих процесів', pl: 'Modułowe komponenty do automatyzacji procesów' } },
    ],
  },

  // ─── COMPLIANCE & GOVERNANCE ─────────────────────────────────────────────────
  compliance: {
    label: { de: 'Governance', en: 'Governance', fr: 'Gouvernance', uk: 'Governance', pl: 'Zarządzanie & Zgodność' },
    title: { de: 'Compliance & Betriebssicherheit', en: 'Compliance & Operational Security', fr: 'Conformité & Sécurité Opérationnelle', uk: 'Комплаєнс & Безпека операцій', pl: 'Compliance & Bezpieczeństwo Operacyjne' },
    sub: {
      de: 'Regulierte Umgebungen erfordern absolute Struktur und Nachvollziehbarkeit.',
      en: 'Regulated environments require absolute structure and traceability.',
      fr: 'Les environnements réglementés exigent une structure et une traçabilité strictes.',
      uk: 'Регульовані середовища вимагають абсолютної структури та прозорості.',
      pl: 'Środowiska regulowane wymagają bezwzględnej struktury i pełnej identyfikowalności.',
    },
    cards: [
      {
        title: { de: 'Betrieb in regulierter Umgebung', en: 'Operations in regulated environments', fr: 'Conformité KRITIS', uk: 'Відповідність KRITIS', pl: 'Zgodność z KRITIS' },
        status: 'verified',
        statusLabel: { de: 'LAUT ZEUGNIS', en: 'ACC. TO REFERENCE', fr: 'Vérifié', uk: 'Перевірено', pl: 'Zweryfikowano' },
        items: [
          { de: 'Rollenbasierte Rechtevergabe nach Least Privilege', en: 'Role-based permission assignment according to Least Privilege', fr: 'Administration d\'infrastructure critique nationale chez JoBITS', uk: 'Адміністрування всенімецької KRITIS-інфраструктури в JoBITS', pl: 'Administracja ogólnokrajową infrastrukturą KRITIS w JoBITS' },
          { de: 'Dokumentation jeder Änderung im Ticketsystem', en: 'Documentation of every change in the ticketing system', fr: 'Séparation stricte des permissions et des rôles (Moindre Privilège)', uk: 'Суворий розподіл прав і ролей (Least Privilege)', pl: 'Ścisły podział uprawnień i ról (Zasada Najmniejszych Przywilejów)' },
          { de: 'Tätigkeit in einem KRITIS-relevanten Umfeld', en: 'Activity in a KRITIS-relevant environment', fr: 'Traçabilité complète des modifications et pistes d\'audit', uk: 'Повне документування змін та аудит-трейли', pl: 'Pełna dokumentacja zmian i ścieżki audytu' },
        ],
      },
      {
        title: 'Identity & Access Management',
        status: 'verified',
        statusLabel: { de: 'BELEGT', en: 'VERIFIED', fr: 'Vérifié', uk: 'Перевірено', pl: 'Zweryfikowano' },
        items: [
          { de: '315 Benutzerverwaltungsvorgänge: Neuanlage, Änderung, Löschung', en: '315 user management processes: creation, modification, deletion', fr: 'Gestion des utilisateurs et groupes structurée en RBAC', uk: 'Керування користувачами та групами за моделлю RBAC', pl: 'Zarządzanie użytkownikami i grupami oparte na strukturze RBAC' },
          { de: 'Rechte für Fachanwendungen und Lizenzsteuerung über AD-Gruppen', en: 'Rechte für Fachanwendungen und Lizenzsteuerung über AD-Gruppen', fr: 'Stratégies Conditional Access Microsoft Entra ID', uk: 'Політики Conditional Access у Microsoft Entra ID', pl: 'Zasady Microsoft Entra ID Conditional Access' },
          { de: 'Einrichtung und Entstörung von 2FA und SSO', en: 'Setup and troubleshooting of 2FA and SSO', fr: 'rund 90.000 objets AD sous gouvernance centralisée', uk: 'rund 90.000 об\'єктів AD під централізованим керуванням', pl: 'rund 90.000 obiektów AD pod centralnym nadzorem' },
        ],
      },
      {
        title: { de: 'Endpoint & Perimeter Security', en: 'Endpoint & Perimeter Security', fr: 'Sécurité Endpoints & Périmètre', uk: 'Безпека кінцевих пристроїв & Периметр', pl: 'Bezpieczeństwo Endpointów & Obwodu' },
        status: 'active',
        statusLabel: { de: 'Aktiv', en: 'Active', fr: 'Actif', uk: 'Активно', pl: 'Aktywne' },
        items: [
          { de: 'FortiClient- und Sophos-Endpoint-Verwaltung', en: 'FortiClient and Sophos endpoint management', fr: 'Gestion des endpoints FortiClient & Sophos en KRITIS', uk: 'Керування FortiClient & Sophos у KRITIS', pl: 'Zarządzanie endpointami FortiClient i Sophos w KRITIS' },
          
          { de: 'Sicherheitskonforme Windows-11-Migration via Deskcenter', en: 'Security-compliant Windows 11 migration via Deskcenter', fr: 'Migration sécurisée vers Windows 11 via Deskcenter', uk: 'Безпечна міграція на Windows 11 через Deskcenter', pl: 'Bezpieczna migracja do Windows 11 z wykorzystaniem Deskcenter' },
        ],
      },
      {
        title: 'KKEEY Standard — Methodik',
        status: 'active',
        statusLabel: { de: 'EIGENE METHODIK', en: 'OWN METHODOLOGY', fr: 'En Production', uk: 'У продакшні', pl: 'W Produkcji' },
        items: [
          { de: 'Dokumentierte Methodik für reproduzierbare Fehlerdiagnose', en: 'Documented methodology for reproducible fault diagnosis', fr: 'Méthodologie documentée pour un diagnostic reproductible', uk: 'Документована методологія відтворюваної діагностики помилок', pl: 'Udokumentowana metodologia powtarzalnej diagnostyki usterek' },
          { de: 'Strukturierte Störungsanalyse statt Trial-and-Error', en: 'Structured incident analysis instead of trial and error', fr: 'Analyse structurée des incidents plutôt que par tâtonnement', uk: 'Структурований аналіз інцидентів замість методу спроб і помилок', pl: 'Strukturalna analiza incydentów zamiast metody prób i błędów' },
          { de: 'Im eigenen Support-Alltag angewendet', en: 'Applied in daily support operations', fr: 'Vérifié en exploitation critique de production', uk: 'Перевірено в реальному продуктивному середовищі KRITIS', pl: 'Sprawdzona w operacjach produkcyjnych KRITIS' },
        ],
      },
    ],
  },

  // ─── IMPACT / CASE STORIES ───────────────────────────────────────────────────
  impact: {
    label: { de: 'Impact', en: 'Impact', fr: 'Impact', uk: 'Результати', pl: 'Wpływ & Wyniki' },
    title: { de: 'Messbare Ergebnisse.', en: 'Measurable Results.', fr: 'Résultats Mesurables.', uk: 'Вимірні результати.', pl: 'Mierzalne Rezultaty.' },
    sub: {
      de: 'Omnitracker-Auswertung, Johanniter Bundes-IT, Dezember 2025 bis April 2026.',
      en: 'Omnitracker evaluation, Johanniter Bundes-IT, December 2025 to April 2026.',
      fr: 'Jalons opérationnels issus de 15 ans d\'ingénierie système.',
      uk: 'Практичні досягнення за 15 років системного адміністрування.',
      pl: 'Praktyczne kamienie milowe z 15 lat zarządzania systemami.',
    },
    cases: [
      {
        metric: '553',
        unit: '',
        title: { de: 'eindeutige Tickets', en: 'unique tickets', fr: 'tickets uniques', uk: 'унікальні тікети', pl: 'unikalne zgłoszenia' },
        desc: { de: '471 Service Requests · 82 Incidents', en: '471 Service Requests · 82 Incidents', fr: '471 Service Requests · 82 Incidents', uk: '471 Service Requests · 82 Incidents', pl: '471 Service Requests · 82 Incidents' },
        tag: { de: '', en: '', fr: '', uk: '', pl: '' },
      },
      {
        metric: '754',
        unit: '',
        title: { de: 'gebuchte Vorgänge', en: 'booked processes', fr: 'processus enregistrés', uk: 'зареєстровані процеси', pl: 'zarejestrowane procesy' },
        desc: { de: '2. Dezember 2025 bis 22. April 2026', en: 'December 2, 2025 to April 22, 2026', fr: '2 Décembre 2025 au 22 Avril 2026', uk: '2 грудня 2025 - 22 квітня 2026', pl: '2 grudnia 2025 do 22 kwietnia 2026' },
        tag: { de: '', en: '', fr: '', uk: '', pl: '' },
      },
      {
        metric: '366,2',
        unit: { de: 'h', en: 'h', fr: 'h', uk: 'г', pl: 'godz' },
        title: { de: 'dokumentierte Bearbeitungszeit', en: 'documented processing time', fr: 'temps de traitement documenté', uk: 'задокументований час обробки', pl: 'udokumentowany czas przetwarzania' },
        desc: { de: '21.971 Minuten · 82 Tage mit Buchungen', en: '21,971 minutes · 82 days with bookings', fr: '21.971 minutes · 82 jours avec saisies', uk: '21.971 хвилин · 82 дні із записами', pl: '21.971 minut · 82 dni z wpisami' },
        tag: { de: '', en: '', fr: '', uk: '', pl: '' },
      },
      {
        metric: '12',
        unit: '',
        title: { de: 'Organisationseinheiten', en: 'organizational units', fr: 'unités organisationnelles', uk: 'організаційні одиниці', pl: 'jednostki organizacyjne' },
        desc: { de: '9 Landesverbände, Bundesgeschäftsstelle, JoBITS und Akkon-Hochschule', en: '9 regional associations, federal headquarters, JoBITS and Akkon University', fr: '9 associations régionales, siège fédéral, JoBITS et université Akkon', uk: '9 регіональних асоціацій, федеральна штаб-квартира, JoBITS та університет Akkon', pl: '9 stowarzyszeń regionalnych, siedziba federalna, JoBITS i Uniwersytet Akkon' },
        tag: { de: '', en: '', fr: '', uk: '', pl: '' },
      },
    ],
  },

  // ─── BERUFSERFAHRUNG ────────────────────────────────────────────────────────
  career: {
    label: { de: 'Werdegang', en: 'Career', fr: 'Parcours', uk: 'Кар\'єра', pl: 'Kariera' },
    title: { de: 'Berufserfahrung', en: 'Work experience', fr: 'Expérience Professionnelle', uk: 'Досвід роботи', pl: 'Doświadczenie Zawodowe' },
    items: [
      {
        period: { de: 'Dez 2025 – Mai 2026', en: 'Dec 2025 – May 2026', fr: 'Déc 2025 – Mai 2026', uk: 'Груд 2025 – Трав 2026', pl: 'Gru 2025 – Maj 2026' },
        role: { de: 'Junior IT-Support Agent mit Aufgaben der Systemadministration', en: 'Junior IT Support Agent with system administration duties', fr: 'Administrateur IT', uk: 'IT-Адміністратор', pl: 'Administrator IT' },
        company: 'Johanniter Bundes-IT-Services',
        active: false,
        desc: {
          de: '553 Tickets und 366 Stunden dokumentierte Bearbeitungszeit für 12 Organisationseinheiten. Bundesweite AD-Umgebung mit rund rund 90.000 Objekten. Benutzer- und Gruppenverwaltung im Active Directory, Citrix-Support, Postfach- und Verteilerverwaltung, Windows-11-Rollout für rund 200 Endpoints mit Deskcenter Studio und angepasstem PowerShell-Skript. Endpoint-Security mit FortiClient und Sophos. Eigenentwicklungen: Tool zur Ticket-Zuweisung und der KKEEY-Standard. Laut Arbeitszeugnis zusätzlich Gruppenrichtlinien, Kerberos, Mail-Flow-Regeln und Citrix-Terminalserver.',
          en: '553 tickets and 366 hours of documented processing time for 12 organizational units. Nationwide AD environment with around 90,000 objects. User and group management in Active Directory, Citrix support, mailbox and distribution list management, Windows 11 rollout for around 200 endpoints with Deskcenter Studio and adapted PowerShell script. Endpoint security with FortiClient and Sophos. Own developments: tool for ticket assignment and the KKEEY standard. According to reference additionally Group Policies, Kerberos, mail flow rules and Citrix terminal servers.',
          fr: 'Administration d\'une infrastructure critique nationale pour rund 90.000 objets AD : Active Directory, Microsoft Entra ID, Citrix (NetScaler), Omnitracker, téléphonie PBX. Déploiement Windows 11 via Deskcenter Studio et scripts PowerShell. Sécurité FortiClient & Sophos. Outil de routage de tickets développé sur mesure.',
          uk: 'Адміністрування загальнонаціональної KRITIS-інфраструктури для rund 90.000 користувачів та AD-об\'єктів: Active Directory, Microsoft Entra ID, Citrix, NetScaler, Omnitracker, Innovaphone PBX. Міграція на Windows 11 через Deskcenter Studio та PowerShell. Безпека FortiClient & Sophos. Власні розробки: інструмент маршрутизації тікетів та стандарт KKEEY.',
          pl: 'Administracja ogólnokrajową infrastrukturą KRITIS dla ponad rund 90.000 użytkowników i obiektów AD: Active Directory, Microsoft Entra ID, Citrix (w tym NetScaler), Omnitracker, Innovaphone PBX. Migracja Windows 11 przez Deskcenter Studio i dedykowany skrypt PowerShell. Bezpieczeństwo punktów końcowych z FortiClient i Sophos. Autorskie rozwiązania: narzędzie do automatycznego przydzielania zgłoszeń oraz standard KKEEY.',
        },
        tags: ['Active Directory', 'Citrix', 'Deskcenter Studio', 'PowerShell', 'Windows 11', 'KRITIS-Umfeld', 'FortiClient', 'Sophos'],
      },
      {
        period: { de: '2010 – 2024 · 14 Jahre', en: '2010 – 2024 · 14 years', fr: '2010 – 2024 · 14 ans', uk: '2010 – 2024 · 14 років', pl: '2010 – 2024 · 14 lat' },
        role: { de: 'Inventory Management & Warenwirtschaft', en: 'Inventory Management & Merchandise Management', fr: 'Responsable IT & Gestion d\'Inventaire', uk: 'IT-Спеціаліст & Керування інвентарем', pl: 'Specjalista IT & Zarządzanie Stanami Magazynowymi' },
        company: 'BAUHAUS',
        active: false,
        desc: {
          de: '14 Jahre operative Praxis in Warenwirtschaft, Inventory Management und Prozessoptimierung. Ich kenne den Arbeitsalltag der Anwender aus erster Hand: welche Prozesse funktionieren und wo Systeme im Betrieb brechen.',
          en: '14 years of operational practice in merchandise management, inventory management and process optimization. I know users’ daily work first-hand: which processes work and where systems break in production.',
          fr: 'Support technique Niveaux 1 à 3, maintenance de l\'ERP commercial, gestion du parc matériel et des processus opérationnels pendant 14 ans. Connaissance concrète des besoins utilisateurs sur le terrain.',
          uk: 'Підтримка користувачів 1–3 рівнів, супровід системи товарообігу, відповідальність за обладнання та робочі процеси. 14 років практичного досвіду в щоденній роботі.',
          pl: 'Wsparcie L1-L3, techniczna obsługa systemów gospodarki towarowej ERP, odpowiedzialność za sprzęt i procesy w bieżącej działalności handlowej. 14 lat praktyki operacyjnej: znam codzienność użytkowników z pierwszej ręki — które procesy działają, a gdzie systemy zawodzą w praktyce.',
        },
        tags: ['Warenwirtschaft', 'Prozessoptimierung', 'Anwenderbetreuung'],
      },
      {
        period: { de: 'seit Juni 2026', en: 'since June 2026', fr: 'depuis Juin 2026', uk: 'з Червня 2026', pl: 'od Czerwca 2026' },
        role: { de: 'IT-Systementwicklung & Prozessautomatisierung', en: 'IT Systems Development & Process Automation', fr: 'Développement Systèmes IT & Automatisation', uk: 'Розробка IT-систем & Автоматизація', pl: 'Doradztwo IT & Automatyzacja Procesów' },
        company: { de: 'Weiterbildung & Eigenprojekte · Gründungsvorbereitung', en: 'Professional Development & Independent Projects · Venture Preparation', fr: 'Formation & Projets Personnels · Préparation de Création', uk: 'Професійний розвиток та власні проєкти · Підготовка до запуску', pl: 'Rozwój zawodowy i projekty własne · Przygotowanie działalności' },
        active: true,
        desc: {
          de: 'Eigenprojekte und fachliche Vertiefung in Systemadministration, IAM, Workflow-Automatisierung und Tool-Entwicklung. Vorbereitung eines künftigen B2B-Angebots für kleine und mittlere Unternehmen.',
          en: 'Independent projects and professional development in system administration, IAM, workflow automation and tool development. Preparing a future B2B offering for small and medium-sized businesses.',
          fr: 'Conseil et implémentation en administration système, automatisation des workflows et développement d\'outils.',
          uk: 'Консалтинг та впровадження рішень із системного адміністрування, автоматизації процесів та розробки інструментів для бізнесу.',
          pl: 'Doradztwo i wdrażanie rozwiązań z zakresu administracji systemami, automatyzacji przepływów pracy i tworzenia narzędzi dla małych i średnich przedsiębiorstw.',
        },
        tags: ['Automatisierung', 'PowerShell', 'Python', 'KMU'],
      },
    ],
  },

  // ─── KERNKOMPETENZEN ────────────────────────────────────────────────────────
  skills: {
    label: { de: 'Kompetenzen', en: 'Skills', fr: 'Compétences', uk: 'Навички', pl: 'Kompetencje' },
    title: { de: 'Kernkompetenzen', en: 'Core competencies', fr: 'Compétences Clés', uk: 'Ключові компетенції', pl: 'Kluczowe Umiejętności' },
    groups: [
      {
        label: { de: 'Identity & Access Management', en: 'Identity & Access Management', fr: 'Gestion des Identités et Accès', uk: 'Identity & Access Management', pl: 'Zarządzanie Tożsamością i Dostępem' },
        items: ['Active Directory', { de: 'Benutzer- & Berechtigungsverwaltung', en: 'User & permissions management', fr: 'Gestion utilisateurs & droits', uk: 'Керування користувачами та правами', pl: 'Zarządzanie użytkownikami i uprawnieniami' }, { de: 'Rechte für Fachanwendungen', en: 'Rights for specialized applications', fr: 'IAM en infrastructure critique', uk: 'IAM у критичних середовищах', pl: 'IAM w środowiskach KRITIS' }],
      },
      {
        label: { de: 'Client & Infrastruktur', en: 'Client & Infrastructure', fr: 'Clients & Infrastructure', uk: 'Клієнти та інфраструктура', pl: 'Stacje Robocze & Infrastruktura' },
        items: [{ de: 'Windows-11-Migrationen', en: 'Windows 11 migrations', fr: 'Migrations Windows 11', uk: 'Міграції на Windows 11', pl: 'Migracje do Windows 11' }, 'Deskcenter Studio', 'Citrix Workspace & Director', 'Omnitracker', 'Innovaphone PBX', { de: 'Hardware-Betreuung', en: 'Hardware support', fr: 'Support Matériel', uk: 'Обслуговування апаратного забезпечення', pl: 'Obsługa sprzętu IT' }],
      },
      {
        label: { de: 'Security & Netzwerk', en: 'Security & Network', fr: 'Sécurité & Réseau', uk: 'Безпека та мережі', pl: 'Bezpieczeństwo & Sieci' },
        items: ['FortiClient', 'Sophos', { de: 'Endpoint Security', en: 'Endpoint Security', fr: 'Sécurité des Endpoints', uk: 'Безпека кінцевих точок', pl: 'Bezpieczeństwo Endpointów' }, { de: 'Phishing- und Spam-Meldungen', en: 'Phishing and spam reports', fr: 'Infrastructures Critiques', uk: 'Критична інфраструктура', pl: 'Infrastruktura Krytyczna' }],
      },
      {
        label: { de: 'Automatisierung & Scripting', en: 'Automation & Scripting', fr: 'Automatisation & Scripting', uk: 'Автоматизація та скрипти', pl: 'Automatyzacja & Skrypty' },
        items: ['PowerShell', 'Python 3.12+', 'TypeScript', 'Docker & Cloud Run', { de: 'Prozessautomatisierung', en: 'Process automation', fr: 'Automatisation des processus', uk: 'Автоматизація процесів', pl: 'Automatyzacja procesów' }, { de: 'Eigene Workflow-Tools', en: 'Custom workflow tools', fr: 'Outils de workflow sur mesure', uk: 'Власні інструменти процесів', pl: 'Dedykowane narzędzia workflow' }],
      },
      {
        label: { de: 'Support & Methodik', en: 'Support & Methodology', fr: 'Support & Méthodologie', uk: 'Підтримка та методологія', pl: 'Wsparcie & Metodologia' },
        items: [{ de: 'Ticketbasierter Support', en: 'Ticket-based support', fr: 'Support N1–N3', uk: 'Підтримка 1–3 рівнів', pl: 'Wsparcie L1–L3' }, { de: 'Ticketsysteme', en: 'Ticketing systems', fr: 'Systèmes de tickets', uk: 'Тікет-системи', pl: 'Systemy zgłoszeniowe' }, { de: 'Warenwirtschaftssysteme', en: 'Merchandise management systems', fr: 'Systèmes ERP', uk: 'Системи обліку товарів', pl: 'Systemy gospodarki towarowej ERP' }, { de: 'Reproduzierbare Fehlerdiagnose', en: 'Reproducible fault diagnosis', fr: 'Diagnostic d\'erreur reproductible', uk: 'Відтворювана діагностика помилок', pl: 'Powtarzalna diagnostyka błędów' }],
      },
      {
        label: { de: 'AI Engineering & Innovation', en: 'AI Engineering & Innovation', fr: 'Ingénierie IA & Innovation', uk: 'AI Інженерія та інновації', pl: 'AI Engineering & Innowacje' },
        items: ['LiveKit 2.x Voice AI', 'Gemini API / Vertex AI', 'Local LLMs (LM Studio)', 'Rust / Tauri 2.0', 'Audio DSP & Metal GPU', { de: 'Agenten-Architekturen', en: 'Agentic Architectures', fr: 'Architectures d\'Agents', uk: 'Агентні архітектури', pl: 'Architektury Agentowe' }],
      },
    ],
  },

  // ─── EIGENE TOOLS & METHODIK ────────────────────────────────────────────────
  tools: {
    label: { de: 'Proof of Work', en: 'Proof of Work', fr: 'Preuve de Réalisation', uk: 'Proof of Work', pl: 'Dowód Kompetencji' },
    title: { de: 'Eigene Tools & Methodik', en: 'Own tools & methodology', fr: 'Outils Personnalisés & Méthodologie', uk: 'Власні інструменти & Методологія', pl: 'Autorskie Narzędzia & Metodologia' },
    sub: {
      de: 'Wo ich im Betrieb Reibung sehe, baue ich Lösungen — die im Team im Einsatz sind.',
      en: 'Where I see friction in operations, I build solutions — used by the team in production.',
      fr: 'Face aux frictions opérationnelles, je conçois des solutions déployées en production.',
      uk: 'Там, де в роботі виникає тертя, я створюю рішення, якими користується вся команда.',
      pl: 'Tam, gdzie widzę nieefektywność w operacjach, buduję rozwiązania — używane przez zespół w produkcji.',
    },
    items: [
      {
        name: { de: 'Ticket-Routing-Automatisierung', en: 'Ticket routing automation', fr: 'Automatisation du routage des tickets', uk: 'Автоматизація маршрутизації тікетів', pl: 'Automatyzacja Routingu Zgłoszeń' },
        sub: { de: '● Im Team-Einsatz · Eigenentwicklung', en: '● Used in production · Internal tool', fr: '● Déployé en équipe · Développement interne', uk: '● У командній роботі · Власна розробка', pl: '● Używane w produkcji · Rozwiązanie własne' },
        desc: {
          de: 'Selbstentwickeltes Tool, das eingehende Support-Tickets regelbasiert dem passenden Bearbeiter zuweist. Ersetzt tägliche manuelle Verteilarbeit.',
          en: 'Self-developed tool that assigns incoming support tickets to the right agent based on rules. Replaces daily manual triage work.',
          fr: 'Outil assignant automatiquement les tickets de support entrants selon des règles précises. Supprime le tri manuel quotidien.',
          uk: 'Власний інструмент, який розподіляє вхідні тікети між фахівцями на основі правил, усуваючи щоденну ручну роботу.',
          pl: 'Autorskie narzędzie przydzielające przychodzące zgłoszenia do właściwego specjalisty na podstawie reguł. Eliminuje codzienną manualną pracę triage.',
        },
      },
      {
        name: 'KKEEY-Standard',
        sub: { de: '● Eigene Methodik', en: '● Own methodology', fr: '● Méthodologie standardisée · Vérifiée', uk: '● Стандартизована методика · Перевірено', pl: '● Standaryzowana metodologia · Zweryfikowano' },
        desc: {
          de: 'Dokumentierte Methodik für strukturierte, reproduzierbare Fehlerdiagnose — damit Störungen nachvollziehbar gelöst werden statt per Trial-and-Error.',
          en: 'Documented methodology for structured, reproducible fault diagnosis — so incidents are resolved traceably instead of by trial and error.',
          fr: 'Méthode documentée pour un diagnostic d\'incident structuré et reproductible sans tâtonnement.',
          uk: 'Документована методика структурованого пошуку та усунення несправностей без хаотичних спроб.',
          pl: 'Udokumentowana metodologia ustrukturyzowanej, powtarzalnej diagnostyki błędów — aby awarie były rozwiązywane w sposób identyfikowalny, a nie metodą prób i błędów.',
        },
      },
      {
        name: 'KKI Agent-Framework',
        sub: { de: '● Eigenes Framework · privat', en: '● Own framework · private', fr: '● Framework actif · Bibliothèque interne', uk: '● Активний фреймворк · Внутрішня бібліотека', pl: '● Aktywny framework · Wewnętrzna biblioteka' },
        desc: {
          de: 'Privat entwickelte Agentenstruktur mit wiederverwendbaren Bausteinen für Automatisierungs-Workflows — die gemeinsame Grundlage meiner eigenen Tools.',
          en: 'Privately developed agent structure with reusable building blocks for automation workflows — the shared foundation of my own tools.',
          fr: 'Architecture d\'agents modulaires et réutilisables pour automatiser les workflows complexes.',
          uk: 'Модульна агентна структура з багаторазовими компонентами для автоматизації складних процесів.',
          pl: 'Prywatnie opracowana struktura agentów z modułowymi komponentami do automatyzacji procesów — wspólny fundament moich autorskich narzędzi.',
        },
      },
    ],
  },

  // ─── NEBENPROJEKTE ──────────────────────────────────────────────────────────
  side: {
    label: { de: 'Zusatzqualifikation', en: 'Additional qualification', fr: 'Compétences Complémentaires', uk: 'Додаткова кваліфікація', pl: 'Dodatkowe Kwalifikacje' },
    title: { de: 'Nebenprojekte: KI-Entwicklung', en: 'Side projects: AI development', fr: 'Projets IA & Innovation', uk: 'Проєкти в сфері штучного інтелекту', pl: 'Projekty Poboczne: Rozwój AI' },
    text: {
      de: 'Neben der Administration entwickle ich KI-gestützte Anwendungen — ein zusätzliches Werkzeug, um Automatisierung weiterzudenken.',
      en: 'Alongside administration I build AI-assisted applications — an additional tool for taking automation further.',
      fr: 'En parallèle de l\'administration, je développe des applications IA pour enrichir les possibilités d\'automatisation.',
      uk: 'Окрім системного адміністрування, я розробляю програми з використанням ШІ для розширення можливостей автоматизації.',
      pl: 'Oprócz administracji tworzę aplikacje wspomagane przez sztuczną inteligencję — dodatkowe narzędzie rozwijające automatyzację.',
    },
    items: [
      { name: 'Claire V2.5 Native Audio', desc: { de: '● v2.5 · öffentlich · Voice-AI-Agent · LiveKit 2.x, Python', en: '● v2.5 · public · Voice AI agent · LiveKit 2.x, Python', fr: '● En production v2.5 · Agent vocal IA · LiveKit 2.x, Python, latence ', uk: '● Продакшн v2.5 · Голосовий AI-агент · LiveKit 2.x, Python, затримка ', pl: '● Wdrożenie v2.5 · Głosowy agent AI · LiveKit 2.x, Python, opóźnienie ' } },
      { name: 'AuraTone AI v2.0', desc: { de: '● Private Codebasis v2.0.0 · Native macOS Audio-Workstation · Tauri 2 (Rust)', en: '● Private Codebasis v2.0.0 · Native macOS Audio-Workstation · Tauri 2 (Rust)', fr: '● Application native v2.0 · macOS Audio Workstation · Tauri 2.0 (Rust), Metal GPU', uk: '● Нативний застосунок v2.0 · macOS Audio Workstation · Tauri 2.0 (Rust), Metal GPU', pl: '● Aplikacja natywna v2.0 · macOS Audio Workstation · Tauri 2.0 (Rust), Metal GPU' } },
      { name: 'KKI Agent-Framework', desc: { de: '● Aktives Framework · Wiederverwendbare Bausteine für Automation-Workflows', en: '● Active framework · Reusable building blocks for automation workflows', fr: '● Framework actif · Modules d\'automatisation réutilisables', uk: '● Активний фреймворк · Багаторазові модулі автоматизації', pl: '● Aktywny framework · Moduły automatyzacji wielokrotnego użytku' } },
    ],
    moreLink: 'https://kkeey.dev/',
    moreLabel: { de: 'Mehr im AI-Portfolio →', en: 'More in the AI portfolio →', fr: 'Découvrir le portfolio IA →', uk: 'Більше в AI-портфоліо →', pl: 'Więcej w portfolio AI →' },
  },

  // ─── KONTAKT ────────────────────────────────────────────────────────────────
  contact: {
    label: { de: 'Kontakt', en: 'Contact', fr: 'Contact', uk: 'Контакти', pl: 'Kontakt' },
    title: { de: 'Lassen Sie uns sprechen.', en: 'Let’s talk.', fr: 'Échangeons ensemble.', uk: 'Почнімо діалог.', pl: 'Porozmawiajmy.' },
    desc: {
      de: 'Offen für Festanstellungen als IT-Administrator, Systemadministrator oder IAM-Specialist. Remote · Hybrid · Arbeitssprachen: Deutsch & Englisch.',
      en: 'Open to full-time roles as IT administrator, system administrator, or IAM specialist. Remote · Hybrid · Working languages: German & English.',
      fr: 'Ouvert aux opportunités en administration système, ingénierie IT ou IAM. Télétravail / Hybride · Langues de travail : allemand et anglais.',
      uk: 'Відкритий до посад IT-адміністратора, системного адміністратора або спеціаліста з IAM. Віддалено / Гібрид · Робочі мови: німецька та англійська.',
      pl: 'Otwarty na stanowiska: Administrator IT, Administrator Systemowy lub Specjalista IAM. Remote · Hybrydowo · Języki robocze: niemiecki i angielski.',
    },
    emails: ['hello@kkeey.dev', 'office@kkeey.dev'],
  },

  // ─── I18N STRINGS ────────────────────────────────────────────────────────────
  modules: {
    nav_praxis: { de: 'Praxis', en: 'Practice', fr: 'Pratique', uk: 'Практика', pl: 'Praktyka' },
    m1_eyebrow1: { de: 'VORGÄNGE PRO BUCHUNGSTAG', en: 'PROCESSES PER BOOKING DAY', fr: 'PROCESSUS PAR JOUR DE SAISIE', uk: 'ПРОЦЕСИ ЗА ДЕНЬ БРОНЮВАННЯ', pl: 'PROCESY NA DZIEŃ REJESTRACJI' },
    m1_title1: { de: 'Vom Einstieg zur vollen Last.', en: 'From onboarding to full load.', fr: 'De l\'intégration à la pleine charge.', uk: 'Від початку до повного навантаження.', pl: 'Od wdrożenia do pełnego obciążenia.' },
    m1_foot1: { de: 'Balken: Vorgänge je Tag mit Buchungen. Zahl darunter: Vorgänge im Monat. April bis 22.04.', en: 'Bars: Processes per day with bookings. Number below: Processes per month. April until 22.04.', fr: 'Barres : Processus par jour avec saisies. Nombre en dessous : Processus par mois. Avril jusqu\'au 22.04.', uk: 'Стовпці: Процеси на день із записами. Число знизу: Процеси на місяць. Квітень до 22.04.', pl: 'Paski: Procesy na dzień z wpisami. Liczba poniżej: Procesy na miesiąc. Kwiecień do 22.04.' },
    m1_eyebrow2: { de: 'BENUTZERVERWALTUNG · MINUTEN PRO VORGANG', en: 'USER MANAGEMENT · MINUTES PER PROCESS', fr: 'GESTION DES UTILISATEURS · MINUTES PAR PROCESSUS', uk: 'КЕРУВАННЯ КОРИСТУВАЧАМИ · ХВИЛИНИ НА ПРОЦЕС', pl: 'ZARZĄDZANIE UŻYTKOWNIKAMI · MINUTY NA PROCES' },
    m1_title2: { de: 'Weniger Zeit je Vorgang.', en: 'Less time per process.', fr: 'Moins de temps par processus.', uk: 'Менше часу на процес.', pl: 'Mniej czasu na proces.' },
    m1_delta: { de: '<strong>−55 %</strong> von Dezember bis April, bei 315 Vorgängen.', en: '<strong>−55 %</strong> from December to April, across 315 processes.', fr: '<strong>−55 %</strong> de décembre à avril, sur 315 processus.', uk: '<strong>−55 %</strong> з грудня по квітень, у 315 процесах.', pl: '<strong>−55 %</strong> od grudnia do kwietnia, w 315 procesach.' },
    m1_foot2: { de: 'Gebuchte Minuten, keine Durchlaufzeit. Aufgabenmix und Buchungsweise beeinflussen die Werte.', en: 'Booked minutes, not lead time. Task mix and booking method affect the values.', fr: 'Minutes saisies, pas le temps de traitement global. Le mix de tâches et la méthode de saisie influencent les valeurs.', uk: 'Заброньовані хвилини, а не загальний час виконання. Набір завдань та спосіб реєстрації впливають на значення.', pl: 'Zarejestrowane minuty, nie czas cyklu. Mieszanka zadań i sposób rejestracji wpływają na wartości.' },
    m2_label: { de: 'Praxis', en: 'Practice', fr: 'Pratique', uk: 'Практика', pl: 'Praktyka' },
    m2_title: { de: 'Technische Tiefe im Alltag.', en: 'Technical depth in everyday operations.', fr: 'Profondeur technique au quotidien.', uk: 'Технічна глибина в повсякденній роботі.', pl: 'Głębia techniczna na co dzień.' },
    m2_sub: { de: 'Anonymisierte Fälle aus der Johanniter Bundes-IT.', en: 'Anonymized cases from Johanniter Bundes-IT.', fr: 'Cas anonymisés de la Johanniter Bundes-IT.', uk: 'Анонімізовані випадки з Johanniter Bundes-IT.', pl: 'Zanonimizowane przypadki z Johanniter Bundes-IT.' },
    m2_eyebrow: { de: 'ARBEITSSCHWERPUNKTE · 754 VORGÄNGE · 366,2 H', en: 'MAIN TASKS · 754 PROCESSES · 366.2 H', fr: 'TÂCHES PRINCIPALES · 754 PROCESSUS · 366,2 H', uk: 'ОСНОВНІ ЗАВДАННЯ · 754 ПРОЦЕСИ · 366,2 Г', pl: 'GŁÓWNE ZADANIA · 754 PROCESY · 366,2 GODZ' },
    m2_l_n: { de: 'Anteil Vorgänge', en: 'Share of processes', fr: 'Part de processus', uk: 'Частка процесів', pl: 'Udział procesów' },
    m2_l_h: { de: 'Anteil Zeit', en: 'Share of time', fr: 'Part de temps', uk: 'Частка часу', pl: 'Udział czasu' },
    m2_row1_title: { de: 'Benutzerverwaltung', en: 'User management', fr: 'Gestion des utilisateurs', uk: 'Керування користувачами', pl: 'Zarządzanie użytkownikami' },
    m2_row1_sub: { de: '315 Vorgänge · 100,3 h', en: '315 processes · 100.3 h', fr: '315 processus · 100,3 h', uk: '315 процесів · 100,3 г', pl: '315 procesów · 100,3 godz' },
    m2_row2_title: { de: 'Clients und Upgrades', en: 'Clients and upgrades', fr: 'Postes clients et mises à niveau', uk: 'Клієнти та оновлення', pl: 'Klienci i aktualizacje' },
    m2_row2_sub: { de: '125 Vorgänge · 129,3 h', en: '125 processes · 129.3 h', fr: '125 processus · 129,3 h', uk: '125 процесів · 129,3 г', pl: '125 procesów · 129,3 godz' },
    m2_row3_title: { de: 'Software und Office', en: 'Software and Office', fr: 'Logiciels et Office', uk: 'Програмне забезпечення та Office', pl: 'Oprogramowanie i Office' },
    m2_row3_sub: { de: '112 Vorgänge · 51,4 h', en: '112 processes · 51.4 h', fr: '112 processus · 51,4 h', uk: '112 процесів · 51,4 г', pl: '112 procesów · 51,4 godz' },
    m2_row4_title: { de: 'Citrix-App-Bereitstellung', en: 'Citrix app deployment', fr: 'Déploiement d\'applications Citrix', uk: 'Розгортання додатків Citrix', pl: 'Wdrażanie aplikacji Citrix' },
    m2_row4_sub: { de: '39 Vorgänge · 18,6 h', en: '39 processes · 18.6 h', fr: '39 processus · 18,6 h', uk: '39 процесів · 18,6 г', pl: '39 procesów · 18,6 godz' },
    m2_row5_title: { de: 'Zoom-Lizenzen', en: 'Zoom licenses', fr: 'Licences Zoom', uk: 'Ліцензії Zoom', pl: 'Licencje Zoom' },
    m2_row5_sub: { de: '30 Vorgänge · 7,3 h', en: '30 processes · 7.3 h', fr: '30 processus · 7,3 h', uk: '30 процесів · 7,3 г', pl: '30 procesów · 7,3 godz' },
    m2_row6_title: { de: 'Allgemein und weitere', en: 'General and other', fr: 'Général et autres', uk: 'Загальні та інше', pl: 'Ogólne i inne' },
    m2_row6_sub: { de: '133 Vorgänge · 59,3 h · u. a. Drucker, MDM, Security, Fachanwendungen', en: '133 processes · 59.3 h · incl. printers, MDM, security, specialized apps', fr: '133 processus · 59,3 h · dont imprimantes, MDM, sécurité, applications spécifiques', uk: '133 процеси · 59,3 г · зокрема принтери, MDM, безпека, спеціалізовані додатки', pl: '133 procesy · 59,3 godz · w tym drukarki, MDM, bezpieczeństwo, aplikacje specjalistyczne' },
    m2_foot: { de: 'Die meisten Vorgänge: Benutzerverwaltung. Die meiste Zeit: Clients, mit 16,6 % der Vorgänge und 35,3 % der gebuchten Zeit.', en: 'Most processes: User management. Most time: Clients, with 16.6% of processes and 35.3% of booked time.', fr: 'La plupart des processus : Gestion des utilisateurs. Le plus de temps : Postes clients, avec 16,6 % des processus et 35,3 % du temps saisi.', uk: 'Найбільше процесів: Керування користувачами. Найбільше часу: Клієнти, з 16,6% процесів і 35,3% заброньованого часу.', pl: 'Najwięcej procesów: Zarządzanie użytkownikami. Najwięcej czasu: Klienci, z 16,6% procesów i 35,3% zarejestrowanego czasu.' },
    m3_p: { de: 'Problem', en: 'Problem', fr: 'Problème', uk: 'Проблема', pl: 'Problem' },
    m3_v: { de: 'Vorgehen', en: 'Approach', fr: 'Approche', uk: 'Підхід', pl: 'Podejście' },
    m3_e: { de: 'Ergebnis', en: 'Result', fr: 'Résultat', uk: 'Результат', pl: 'Wynik' },
    m3_c1_num: { de: '01 / CLIENT RECOVERY', en: '01 / CLIENT RECOVERY', fr: '01 / RÉCUPÉRATION CLIENT', uk: '01 / ВІДНОВЛЕННЯ КЛІЄНТІВ', pl: '01 / ODZYSKIWANIE KLIENTA' },
    m3_c1_title: { de: 'Citrix Workspace neu aufsetzen', en: 'Reinstalling Citrix Workspace', fr: 'Réinstaller Citrix Workspace', uk: 'Перевстановлення Citrix Workspace', pl: 'Ponowna instalacja Citrix Workspace' },
    m3_c1_p: { de: 'Citrix Workspace lief fehlerhaft oder ließ sich nicht neu installieren. Zurücksetzen über die Citrix-Einstellungen und der Standard-Cleanup reichten nicht, weil sich die Anwendung tief in Windows verankert.', en: 'Citrix Workspace was malfunctioning or could not be reinstalled. Resetting via Citrix settings and standard cleanup were insufficient because the application integrates deeply into Windows.', fr: 'Citrix Workspace fonctionnait mal ou ne pouvait pas être réinstallé. Une réinitialisation via les paramètres Citrix et un nettoyage standard ne suffisaient pas car l\'application s\'ancre profondément dans Windows.', uk: 'Citrix Workspace працював з помилками або не перевстановлювався. Скидання через налаштування Citrix і стандартне очищення були недостатніми, оскільки додаток глибоко інтегрується у Windows.', pl: 'Citrix Workspace działał wadliwie lub nie mógł zostać ponownie zainstalowany. Resetowanie przez ustawienia Citrix i standardowe czyszczenie nie wystarczały, ponieważ aplikacja głęboko integruje się z Windows.' },
    m3_c1_v: { de: 'Eigener Ansatz: verbliebene Citrix-Schlüssel im Registrierungseditor und Profilreste in AppData vollständig entfernt, Installation neu ausgeführt.', en: 'Custom approach: completely removed remaining Citrix keys in the Registry Editor and profile remnants in AppData, then re-ran the installation.', fr: 'Approche personnalisée : suppression complète des clés Citrix restantes dans l\'éditeur de registre et des restes de profil dans AppData, puis relance de l\'installation.', uk: 'Власний підхід: повне видалення залишкових ключів Citrix у редакторі реєстру та залишків профілів у AppData, після чого повторна інсталяція.', pl: 'Własne podejście: całkowite usunięcie pozostałych kluczy Citrix w edytorze rejestru oraz resztek profili w AppData, a następnie ponowna instalacja.' },
    m3_c1_e: { de: 'Clients in den meisten Fällen ohne Neuaufsetzen wieder lauffähig.', en: 'Clients operational again in most cases without requiring an OS reinstall.', fr: 'Les clients sont à nouveau opérationnels dans la plupart des cas sans avoir besoin de réinstaller le système.', uk: 'У більшості випадків клієнти знову ставали працездатними без перевстановлення ОС.', pl: 'W większości przypadków klienci ponownie działali bez konieczności przeinstalowania systemu operacyjnego.' },
    m3_c1_meta: { de: 'Kategorie Citrix-App-Bereitstellung: 39 Vorgänge', en: 'Category Citrix App Deployment: 39 processes', fr: 'Catégorie Déploiement d\'applications Citrix : 39 processus', uk: 'Категорія Розгортання додатків Citrix: 39 процесів', pl: 'Kategoria Wdrażanie aplikacji Citrix: 39 procesów' },
    m3_c2_num: { de: '02 / IDENTITY TROUBLESHOOTING', en: '02 / IDENTITY TROUBLESHOOTING', fr: '02 / DÉPANNAGE DES IDENTITÉS', uk: '02 / УСУНЕННЯ НЕПОЛАДОК ІДЕНТИФІКАЦІЇ', pl: '02 / ROZWIĄZYWANIE PROBLEMÓW Z TOŻSAMOŚCIĄ' },
    m3_c2_title: { de: 'SSO-Anmeldung über Airlock entstören', en: 'Troubleshooting SSO login via Airlock', fr: 'Dépannage de la connexion SSO via Airlock', uk: 'Усунення неполадок SSO входу через Airlock', pl: 'Rozwiązywanie problemów z logowaniem SSO przez Airlock' },
    m3_c2_p: { de: 'Die SAML2-SSO-Anmeldung über Airlock schlug fehl.', en: 'SAML2 SSO login via Airlock failed.', fr: 'La connexion SSO SAML2 via Airlock a échoué.', uk: 'Вхід через SAML2 SSO в Airlock не вдався.', pl: 'Logowanie SSO SAML2 przez Airlock zakończyło się niepowodzeniem.' },
    m3_c2_v: { de: 'AD-Konto und Gerätestatus geprüft, Airlock-Logs zur Identity Propagation ausgewertet, Einrichtung im Secure Portal nachvollzogen.', en: 'Checked AD account and device status, analyzed Airlock logs for identity propagation, verified setup in the Secure Portal.', fr: 'Vérification du compte AD et de l\'état de l\'appareil, analyse des journaux Airlock pour la propagation d\'identité, vérification de la configuration dans le portail sécurisé.', uk: 'Перевірка облікового запису AD та стану пристрою, аналіз журналів Airlock для поширення ідентифікації, перевірка налаштувань у Secure Portal.', pl: 'Sprawdzenie konta AD i statusu urządzenia, analiza logów Airlock pod kątem propagacji tożsamości, weryfikacja ustawień w Secure Portal.' },
    m3_c2_e: { de: 'Fehlerursache eingegrenzt, Anmeldung entstört.', en: 'Root cause identified, login successfully restored.', fr: 'Cause première identifiée, connexion rétablie avec succès.', uk: 'Основну причину виявлено, вхід успішно відновлено.', pl: 'Zidentyfikowano przyczynę błędu, logowanie zostało przywrócone.' },
    m3_c2_meta: { de: 'Secure Portal in mindestens 26 Vorgängen genannt', en: 'Secure Portal mentioned in at least 26 processes', fr: 'Portail sécurisé mentionné dans au moins 26 processus', uk: 'Secure Portal згадується принаймні у 26 процесах', pl: 'Secure Portal wspomniany w co najmniej 26 procesach' },
    m3_c3_num: { de: '03 / ENDPOINT MAINTENANCE', en: '03 / ENDPOINT MAINTENANCE', fr: '03 / MAINTENANCE DES POINTS DE TERMINAISON', uk: '03 / ОБСЛУГОВУВАННЯ КІНЦЕВИХ ТОЧОК', pl: '03 / KONSERWACJA PUNKTÓW KOŃCOWYCH' },
    m3_c3_title: { de: 'Homeoffice-Notebooks zurück in die Domäne', en: 'Bringing home office notebooks back into the domain', fr: 'Retour des ordinateurs portables de télétravail dans le domaine', uk: 'Повернення ноутбуків з домашнього офісу в домен', pl: 'Przywracanie laptopów z home office do domeny' },
    m3_c3_p: { de: 'Homeoffice-Notebooks hatten keine Anbindung an die Domäne mehr.', en: 'Home office notebooks lost connection to the domain.', fr: 'Les ordinateurs portables de télétravail ont perdu la connexion au domaine.', uk: 'Ноутбуки для домашнього офісу втратили зв\'язок з доменом.', pl: 'Laptopy z home office straciły połączenie z domeną.' },
    m3_c3_v: { de: 'BIOS und Netzwerktreiber per Fernwartung mit dem HP Image Assistant aktualisiert.', en: 'Updated BIOS and network drivers remotely using HP Image Assistant.', fr: 'Mise à jour du BIOS et des pilotes réseau à distance via HP Image Assistant.', uk: 'Оновлення BIOS та мережевих драйверів віддалено за допомогою HP Image Assistant.', pl: 'Zaktualizowano BIOS i sterowniki sieciowe zdalnie za pomocą HP Image Assistant.' },
    m3_c3_e: { de: 'Notebooks remote wieder an die Domäne angebunden.', en: 'Notebooks successfully reconnected to the domain remotely.', fr: 'Ordinateurs portables reconnectés au domaine à distance avec succès.', uk: 'Ноутбуки успішно перепідключено до домену віддалено.', pl: 'Laptopy pomyślnie podłączono z powrotem do domeny zdalnie.' },
    m3_c3_meta: { de: 'Treiber, BIOS, HP Image Assistant: mindestens 27 Vorgänge, 52 h', en: 'Drivers, BIOS, HP Image Assistant: at least 27 processes, 52 h', fr: 'Pilotes, BIOS, HP Image Assistant : au moins 27 processus, 52 h', uk: 'Драйвери, BIOS, HP Image Assistant: принаймні 27 процесів, 52 г', pl: 'Sterowniki, BIOS, HP Image Assistant: co najmniej 27 procesów, 52 godz' },
    m3_c4_num: { de: '04 / BRANCHENSOFTWARE', en: '04 / INDUSTRY SOFTWARE', fr: '04 / LOGICIELS MÉTIERS', uk: '04 / ГАЛУЗЕВЕ ПРОГРАМНЕ ЗАБЕЗПЕЧЕННЯ', pl: '04 / OPROGRAMOWANIE BRANŻOWE' },
    m3_c4_title: { de: 'Einsatzsoftware für den Rettungsdienst', en: 'Dispatch software for emergency medical services', fr: 'Logiciel d\'intervention pour les services d\'urgence', uk: 'Програмне забезпечення для служби екстреної допомоги', pl: 'Oprogramowanie do zarządzania ratownictwem medycznym' },
    m3_c4_p: { de: 'Clients in Rettungsdienst-Einsatzfahrzeugen benötigten LARDIS Mangora2 bzw. LARDIS:ONE.', en: 'Clients in emergency vehicles required LARDIS Mangora2 or LARDIS:ONE.', fr: 'Les clients dans les véhicules d\'urgence nécessitaient LARDIS Mangora2 ou LARDIS:ONE.', uk: 'Клієнти в автомобілях швидкої допомоги потребували LARDIS Mangora2 або LARDIS:ONE.', pl: 'Klienci w pojazdach ratunkowych wymagali LARDIS Mangora2 lub LARDIS:ONE.' },
    m3_c4_v: { de: 'Installation per Remote-Zugriff auf den Ziel-Clients, Anfrage dokumentiert und zuständigkeitsgerecht abgeschlossen.', en: 'Remote installation on the target clients, request documented and closed according to responsibilities.', fr: 'Installation à distance sur les clients cibles, demande documentée et clôturée selon les responsabilités.', uk: 'Віддалене встановлення на цільових клієнтах, запит задокументовано та закрито відповідно до обов\'язків.', pl: 'Zdalna instalacja na klientach docelowych, zgłoszenie udokumentowane i zamknięte zgodnie z uprawnieniami.' },
    m3_c4_e: { de: 'Software auf den Fahrzeug-Clients bereitgestellt.', en: 'Software successfully deployed on vehicle clients.', fr: 'Logiciel déployé avec succès sur les clients des véhicules.', uk: 'Програмне забезпечення успішно розгорнуто на клієнтах автомобілів.', pl: 'Oprogramowanie pomyślnie wdrożone na klientach w pojazdach.' },
    m3_c4_meta: { de: 'Fernwartung per TeamViewer in 90 Tickets', en: 'Remote support via TeamViewer in 90 tickets', fr: 'Support à distance via TeamViewer dans 90 tickets', uk: 'Віддалена підтримка через TeamViewer у 90 тікетах', pl: 'Wsparcie zdalne przez TeamViewer w 90 zgłoszeniach' },
    m3_c5_num: { de: '05 / ROLLOUT & MIGRATION', en: '05 / ROLLOUT & MIGRATION', fr: '05 / DÉPLOIEMENT & MIGRATION', uk: '05 / РОЗГОРТАННЯ ТА МІГРАЦІЯ', pl: '05 / WDROŻENIA I MIGRACJE' },
    m3_c5_title: { de: 'Windows-11-Rollout mit Domänenmigration', en: 'Windows 11 rollout with domain migration', fr: 'Déploiement de Windows 11 avec migration de domaine', uk: 'Розгортання Windows 11 з міграцією домену', pl: 'Wdrożenie Windows 11 z migracją domeny' },
    m3_c5_p: { de: 'Verteilte Clients bis in Kita-Standorte liefen auf alten Ständen und hingen in einer Legacy-Domäne.', en: 'Distributed clients across various locations including daycares were running outdated versions and were stuck in a legacy domain.', fr: 'Des clients répartis sur plusieurs sites, y compris des garderies, fonctionnaient sur d\'anciennes versions et étaient bloqués dans un domaine hérité.', uk: 'Розподілені клієнти на різних локаціях, включаючи дитячі садки, працювали на застарілих версіях і залишалися в застарілому домені.', pl: 'Rozproszeni klienci w różnych lokalizacjach, w tym przedszkolach, działali na przestarzałych wersjach i pozostawali w starszej domenie.' },
    m3_c5_v: { de: 'Upgrade auf Windows 11 Enterprise 24H2/25H2 im Paket mit Office 2024 und Citrix Workspace, BIOS-Updates für HP und Fujitsu, Wechsel in die Zieldomäne mit neuer Kerberos-Vertrauensstellung. Steuerung über ein Kanban-Board, wöchentlicher Abgleich im Team.', en: 'Upgrade to Windows 11 Enterprise 24H2/25H2 bundled with Office 2024 and Citrix Workspace, BIOS updates for HP and Fujitsu, transition to the target domain with a new Kerberos trust. Managed via a Kanban board with weekly team syncs.', fr: 'Mise à niveau vers Windows 11 Enterprise 24H2/25H2 avec Office 2024 et Citrix Workspace, mises à jour du BIOS pour HP et Fujitsu, transition vers le domaine cible avec une nouvelle approbation Kerberos. Gestion via un tableau Kanban, synchronisation hebdomadaire en équipe.', uk: 'Оновлення до Windows 11 Enterprise 24H2/25H2 разом із Office 2024 та Citrix Workspace, оновлення BIOS для HP та Fujitsu, перехід до цільового домену з новими довіреними відносинами Kerberos. Управління через Kanban-дошку, щотижнева синхронізація команди.', pl: 'Aktualizacja do Windows 11 Enterprise 24H2/25H2 wraz z Office 2024 i Citrix Workspace, aktualizacje BIOS dla HP i Fujitsu, przejście do domeny docelowej z nowym zaufaniem Kerberos. Zarządzanie przez tablicę Kanban, cotygodniowa synchronizacja w zespole.' },
    m3_c5_e: { de: 'Rund 200 Endpoints migriert, überwiegend eigenverantwortlich.', en: 'Around 200 endpoints migrated, mostly autonomously.', fr: 'Environ 200 points de terminaison migrés, en grande partie de manière autonome.', uk: 'Мігрувало близько 200 кінцевих точок, переважно самостійно.', pl: 'Zmigrowano około 200 punktów końcowych, w większości samodzielnie.' },
    m3_c5_meta: { de: 'Projektsteuerung über MeisterTask, im Ticketsystem nur die Incidents', en: 'Project management via MeisterTask, only incidents in the ticketing system', fr: 'Gestion de projet via MeisterTask, seuls les incidents dans le système de tickets', uk: 'Управління проєктами через MeisterTask, у системі тікетів лише інциденти', pl: 'Zarządzanie projektem przez MeisterTask, w systemie zgłoszeń tylko incydenty' },
    m3_c6_num: { de: '06 / NETZWERK & VIRTUALISIERUNG', en: '06 / NETWORK & VIRTUALIZATION', fr: '06 / RÉSEAU & VIRTUALISATION', uk: '06 / МЕРЕЖА ТА ВІРТУАЛІЗАЦІЯ', pl: '06 / SIEĆ I WIRTUALIZACJA' },
    m3_c6_title: { de: 'DNS-Korrektur und Citrix-Session-Analyse', en: 'DNS correction and Citrix session analysis', fr: 'Correction DNS et analyse des sessions Citrix', uk: 'Корекція DNS та аналіз сеансів Citrix', pl: 'Korekta DNS i analiza sesji Citrix' },
    m3_c6_p: { de: 'Netzwerkstörungen an Clients einer Rettungswache am Flughafen BER, auffällige Citrix-Sitzungen.', en: 'Network issues on clients at an emergency station at BER airport, unusual Citrix sessions.', fr: 'Problèmes réseau sur les clients d\'une station d\'urgence à l\'aéroport BER, sessions Citrix inhabituelles.', uk: 'Проблеми з мережею на клієнтах станції швидкої допомоги в аеропорту BER, незвичайні сеанси Citrix.', pl: 'Problemy z siecią u klientów na stacji pogotowia ratunkowego na lotnisku BER, nietypowe sesje Citrix.' },
    m3_c6_v: { de: 'Diagnose per ipconfig und Netzwerkbefehlen, fehlerhafte DNS-Einstellungen im Netzwerkraum korrigiert, aktive Sitzungen im Citrix Director ausgewertet.', en: 'Diagnosis via ipconfig and network commands, corrected faulty DNS settings in the network room, analyzed active sessions in Citrix Director.', fr: 'Diagnostic via ipconfig et commandes réseau, correction des paramètres DNS défectueux dans la salle réseau, analyse des sessions actives dans Citrix Director.', uk: 'Діагностика за допомогою ipconfig та мережевих команд, виправлення помилкових налаштувань DNS в мережевій кімнаті, аналіз активних сеансів у Citrix Director.', pl: 'Diagnoza za pomocą ipconfig i poleceń sieciowych, korekta błędnych ustawień DNS w pomieszczeniu sieciowym, analiza aktywnych sesji w Citrix Director.' },
    m3_c6_e: { de: 'Verbindungen wiederhergestellt, Fehlerbilder sitzungsgenau eingegrenzt.', en: 'Connections restored, errors isolated to specific sessions.', fr: 'Connexions rétablies, erreurs isolées par session.', uk: 'З\'єднання відновлено, помилки локалізовано до конкретних сеансів.', pl: 'Połączenia przywrócone, błędy odizolowane dla konkretnych sesji.' },
    m3_c6_meta: { de: 'Über den eigenen Aufgabenbereich hinaus', en: 'Beyond regular scope of duties', fr: 'Au-delà du champ de responsabilités habituel', uk: 'Поза межами звичайних обов\'язків', pl: 'Poza regularnym zakresem obowiązków' },
    m4_eyebrow: { de: 'NACHWEIS-MATRIX', en: 'EVIDENCE MATRIX', fr: 'MATRICE DE PREUVES', uk: 'МАТРИЦЯ ДОКАЗІВ', pl: 'MACIERZ DOWODÓW' },
    m4_legend: { de: '<span class="kk-on">●</span> belegt <span class="kk-off">–</span> keine gesonderte Quelle <span class="kk-min">≥</span> Mindestwert aus Stichwortzählung', en: '<span class="kk-on">●</span> verified <span class="kk-off">–</span> no separate source <span class="kk-min">≥</span> minimum value from keyword count', fr: '<span class="kk-on">●</span> vérifié <span class="kk-off">–</span> aucune source séparée <span class="kk-min">≥</span> valeur minimale par comptage de mots-clés', uk: '<span class="kk-on">●</span> перевірено <span class="kk-off">–</span> немає окремого джерела <span class="kk-min">≥</span> мінімальне значення за підрахунком ключових слів', pl: '<span class="kk-on">●</span> zweryfikowano <span class="kk-off">–</span> brak osobnego źródła <span class="kk-min">≥</span> minimalna wartość z liczenia słów kluczowych' },
    m4_th1: { de: 'Kompetenzfeld', en: 'Competency Area', fr: 'Domaine de compétence', uk: 'Сфера компетенції', pl: 'Obszar kompetencji' },
    m4_th2: { de: 'Vorgänge', en: 'Processes', fr: 'Processus', uk: 'Процеси', pl: 'Procesy' },
    m4_th3: { de: 'Zeugnis', en: 'Reference', fr: 'Certificat de travail', uk: 'Рекомендація', pl: 'Referencje' },
    m4_th4: { de: 'Kurs', en: 'Course', fr: 'Cours', uk: 'Курс', pl: 'Kurs' },
    m4_th5: { de: 'Projekt', en: 'Project', fr: 'Projet', uk: 'Проєкт', pl: 'Projekt' },
    m4_g1: { de: 'Berufspraxis · Johanniter Bundes-IT', en: 'Professional Practice · Johanniter Bundes-IT', fr: 'Pratique professionnelle · Johanniter Bundes-IT', uk: 'Професійна практика · Johanniter Bundes-IT', pl: 'Praktyka zawodowa · Johanniter Bundes-IT' },
    m4_r1: { de: 'IT Service Management', en: 'IT Service Management', fr: 'Gestion des services informatiques', uk: 'Управління ІТ-послугами', pl: 'Zarządzanie usługami IT' },
    m4_r2: { de: 'Benutzer- und Gruppenverwaltung', en: 'User and group management', fr: 'Gestion des utilisateurs et des groupes', uk: 'Керування користувачами та групами', pl: 'Zarządzanie użytkownikami i grupami' },
    m4_r3: { de: 'Clients und Windows 11', en: 'Clients and Windows 11', fr: 'Postes clients et Windows 11', uk: 'Клієнти та Windows 11', pl: 'Klienci i Windows 11' },
    m4_r4: { de: 'Software und Office', en: 'Software and Office', fr: 'Logiciels et Office', uk: 'Програмне забезпечення та Office', pl: 'Oprogramowanie i Office' },
    m4_r5: { de: 'Exchange und Postfächer', en: 'Exchange and mailboxes', fr: 'Exchange et boîtes aux lettres', uk: 'Exchange та поштові скриньки', pl: 'Exchange i skrzynki pocztowe' },
    m4_r6: { de: 'Fachanwendungen', en: 'Specialized applications', fr: 'Applications spécifiques', uk: 'Спеціалізовані додатки', pl: 'Aplikacje specjalistyczne' },
    m4_r7: { de: 'Citrix-Bereitstellung', en: 'Citrix deployment', fr: 'Déploiement Citrix', uk: 'Розгортання Citrix', pl: 'Wdrażanie Citrix' },
    m4_r8: { de: 'Lizenzsteuerung (Zoom)', en: 'License control (Zoom)', fr: 'Gestion des licences (Zoom)', uk: 'Контроль ліцензій (Zoom)', pl: 'Zarządzanie licencjami (Zoom)' },
    m4_r9: { de: 'SSO und 2FA', en: 'SSO and 2FA', fr: 'SSO et 2FA', uk: 'SSO та 2FA', pl: 'SSO i 2FA' },
    m4_r10: { de: 'Mobile Geräte und MDM', en: 'Mobile devices and MDM', fr: 'Appareils mobiles et MDM', uk: 'Мобільні пристрої та MDM', pl: 'Urządzenia mobilne i MDM' },
    m4_r11: { de: 'Security-Meldungen', en: 'Security reports', fr: 'Rapports de sécurité', uk: 'Звіти про безпеку', pl: 'Raporty bezpieczeństwa' },
    m4_r12: { de: 'Scripting und Automatisierung', en: 'Scripting and automation', fr: 'Scripting et automatisation', uk: 'Скриптинг та автоматизація', pl: 'Skryptowanie i automatyzacja' },
    m4_g2: { de: 'Eigenentwicklung', en: 'Custom Development', fr: 'Développement personnalisé', uk: 'Власна розробка', pl: 'Własny rozwój' },
    m4_r13: { de: 'Realtime Voice AI', en: 'Realtime Voice AI', fr: 'IA vocale en temps réel', uk: 'Голосовий ШІ в реальному часі', pl: 'Głosowa sztuczna inteligencja w czasie rzeczywistym' },
    m4_r14: { de: 'Agenten- und Kontextarchitektur', en: 'Agent and context architecture', fr: 'Architecture d\'agents et de contexte', uk: 'Архітектура агентів та контексту', pl: 'Architektura agentów i kontekstu' },
    m4_r15: { de: 'Cloud und Identity-Grundlagen', en: 'Cloud and Identity basics', fr: 'Bases du Cloud et de l\'Identité', uk: 'Основи хмари та ідентифікації', pl: 'Podstawy chmury i tożsamości' },
    m4_r16: { de: 'Local-first Engineering', en: 'Local-first Engineering', fr: 'Ingénierie Local-first', uk: 'Local-first інженерія', pl: 'Inżynieria Local-first' },
    m4_foot: { de: 'Vorgänge: OmniTracker-Export, 02.12.2025 bis 22.04.2026. Zahlen ohne ≥ stammen aus der Ticketkategorie.', en: 'Processes: OmniTracker export, 02.12.2025 to 22.04.2026. Numbers without ≥ originate from the ticket category.', fr: 'Processus : Export OmniTracker, du 02.12.2025 au 22.04.2026. Les nombres sans ≥ proviennent de la catégorie de ticket.', uk: 'Процеси: Експорт з OmniTracker, з 02.12.2025 до 22.04.2026. Числа без ≥ походять з категорії тікетів.', pl: 'Procesy: Eksport z OmniTracker, od 02.12.2025 do 22.04.2026. Liczby bez ≥ pochodzą z kategorii zgłoszenia.' },
    m5_eyebrow: { de: 'TOOL-STACK AUS DER PRAXIS', en: 'TOOL STACK FROM PRACTICE', fr: 'STACK D\'OUTILS EN PRATIQUE', uk: 'ІНСТРУМЕНТАРІЙ З ПРАКТИКИ', pl: 'ZESTAW NARZĘDZI W PRAKTYCE' },
    m5_legend: { de: '<span class="kk-hot">Tool <b>40</b></span> in mindestens 40 Vorgängen genannt, Zahl als Mindestwert', en: '<span class="kk-hot">Tool <b>40</b></span> mentioned in at least 40 processes, number as minimum value', fr: '<span class="kk-hot">Outil <b>40</b></span> mentionné dans au moins 40 processus, nombre comme valeur minimale', uk: '<span class="kk-hot">Інструмент <b>40</b></span> згаданий принаймні в 40 процесах, число як мінімальне значення', pl: '<span class="kk-hot">Narzędzie <b>40</b></span> wspomniane w co najmniej 40 procesach, liczba jako wartość minimalna' },
    m5_h1: { de: 'Identität und Zugriff', en: 'Identity and Access', fr: 'Identité et Accès', uk: 'Ідентифікація та Доступ', pl: 'Tożsamość i Dostęp' },
    m5_h2: { de: 'Endpoint und Fernwartung', en: 'Endpoint and Remote Support', fr: 'Postes clients et Support à distance', uk: 'Кінцеві точки та Віддалена підтримка', pl: 'Punkty końcowe i Wsparcie zdalne' },
    m5_h3: { de: 'Microsoft 365 und Kommunikation', en: 'Microsoft 365 and Communication', fr: 'Microsoft 365 et Communication', uk: 'Microsoft 365 та Комунікація', pl: 'Microsoft 365 i Komunikacja' },
    m5_h4: { de: 'Citrix und Remote', en: 'Citrix and Remote', fr: 'Citrix et Télétravail', uk: 'Citrix та Віддалена робота', pl: 'Citrix i Praca zdalna' },
    m5_h5: { de: 'Service Management', en: 'Service Management', fr: 'Gestion des services', uk: 'Управління послугами', pl: 'Zarządzanie usługami' },
    m5_h6: { de: 'Fachanwendungen', en: 'Specialized applications', fr: 'Applications spécifiques', uk: 'Спеціалізовані додатки', pl: 'Aplikacje specjalistyczne' },
    m5_h7: { de: 'Mobile und Telekommunikation', en: 'Mobile and Telecommunications', fr: 'Mobile et Télécommunications', uk: 'Мобільний зв\'язок та Телекомунікації', pl: 'Telefony komórkowe i Telekomunikacja' },
    m6_title: { de: 'Zertifikate und Nachweise', en: 'Certificates and Credentials', fr: 'Certificats et Preuves', uk: 'Сертифікати та Докази', pl: 'Certyfikaty i Poświadczenia' },
    m6_b_emp: { de: 'Arbeitgeberbestätigt', en: 'Employer verified', fr: 'Vérifié par l\'employeur', uk: 'Підтверджено роботодавцем', pl: 'Potwierdzone przez pracodawcę' },
    m6_b_course: { de: 'Kursnachweis', en: 'Course certificate', fr: 'Certificat de cours', uk: 'Сертифікат курсу', pl: 'Certyfikat ukończenia kursu' },
    m6_b_learn: { de: 'Lernfeld', en: 'Learning area', fr: 'Domaine d\'apprentissage', uk: 'Сфера навчання', pl: 'Obszar nauki' },
    m6_c1_title: { de: 'Cisco Certified Support Technician', en: 'Cisco Certified Support Technician', fr: 'Cisco Certified Support Technician', uk: 'Cisco Certified Support Technician', pl: 'Cisco Certified Support Technician' },
    m6_c1_p: { de: 'CCST · im Johanniter-Zeugnis genannt', en: 'CCST · mentioned in Johanniter reference', fr: 'CCST · mentionné dans le certificat Johanniter', uk: 'CCST · згадано в рекомендації Johanniter', pl: 'CCST · wspomniany w referencjach Johanniter' },
    m6_c2_title: { de: 'Microsoft Azure Fundamentals', en: 'Microsoft Azure Fundamentals', fr: 'Microsoft Azure Fundamentals', uk: 'Microsoft Azure Fundamentals', pl: 'Microsoft Azure Fundamentals' },
    m6_c2_p: { de: 'AZ-900 · Kursnachweis Teil 1 liegt vor', en: 'AZ-900 · Course certificate part 1 available', fr: 'AZ-900 · Certificat de cours partie 1 disponible', uk: 'AZ-900 · Сертифікат курсу частина 1 доступна', pl: 'AZ-900 · Certyfikat kursu część 1 dostępna' },
    m6_c3_title: { de: 'ITIL', en: 'ITIL', fr: 'ITIL', uk: 'ITIL', pl: 'ITIL' },
    m6_c3_p: { de: 'Stufe wird mit dem Prüfungsnachweis ergänzt', en: 'Level will be added with exam certificate', fr: 'Le niveau sera ajouté avec le certificat d\'examen', uk: 'Рівень буде додано разом із сертифікатом про іспит', pl: 'Poziom zostanie dodany wraz z certyfikatem egzaminacyjnym' },
    m6_c4_title: { de: 'Microsoft Entra ID', en: 'Microsoft Entra ID', fr: 'Microsoft Entra ID', uk: 'Microsoft Entra ID', pl: 'Microsoft Entra ID' },
    m6_c4_p: { de: 'Grundkurs · Identitätsverwaltung', en: 'Basic course · Identity management', fr: 'Cours de base · Gestion des identités', uk: 'Базовий курс · Керування ідентифікацією', pl: 'Kurs podstawowy · Zarządzanie tożsamością' },
    m6_c5_title: { de: 'Microsoft 365', en: 'Microsoft 365', fr: 'Microsoft 365', uk: 'Microsoft 365', pl: 'Microsoft 365' },
    m6_c5_p: { de: 'MS-900 · kein Prüfungsnachweis veröffentlicht', en: 'MS-900 · no exam certificate published', fr: 'MS-900 · aucun certificat d\'examen publié', uk: 'MS-900 · сертифікат про іспит не опубліковано', pl: 'MS-900 · brak opublikowanego certyfikatu egzaminacyjnego' },
  },
  i18n: {
    navOverview:   { de: 'Überblick',     en: 'Overview',   fr: 'Aperçu',      uk: 'Огляд',       pl: 'Przegląd' },
    navSystems:    { de: 'Systeme',       en: 'Systems',    fr: 'Systèmes',    uk: 'Системи',     pl: 'Systemy' },
    navAutomation: { de: 'Automation',    en: 'Automation', fr: 'Automation',  uk: 'Автоматизація', pl: 'Automatyzacja' },
    navCareer:     { de: 'Werdegang',     en: 'Career',     fr: 'Parcours',    uk: 'Кар\'єра',    pl: 'Kariera' },
    navSkills:     { de: 'Skills',        en: 'Skills',     fr: 'Skills',      uk: 'Навички',     pl: 'Umiejętności' },
    navContact:    { de: 'Kontakt',       en: 'Contact',    fr: 'Contact',     uk: 'Контакти',    pl: 'Kontakt' },
    namePH:        { de: 'Ihr Name',      en: 'Your name',  fr: 'Votre nom',   uk: 'Ваше ім\'я',  pl: 'Twoje imię i nazwisko' },
    emailPH:       { de: 'Ihre E-Mail',   en: 'Your email', fr: 'Votre e-mail',uk: 'Ваш Email',   pl: 'Twój adres e-mail' },
    msgPH:         { de: 'Ihre Nachricht…', en: 'Your message…', fr: 'Votre message…', uk: 'Ваше повідомлення…', pl: 'Twoja wiadomość…' },
    submitLabel:   { de: 'Nachricht senden →', en: 'Send message →', fr: 'Envoyer le message →', uk: 'Надіслати повідомлення →', pl: 'Wyślij wiadomość →' },
    sentMsg:       { de: '✓ Nachricht gesendet — ich melde mich zeitnah.', en: '✓ Message sent — I will reply promptly.', fr: '✓ Message envoyé — réponse rapide assurée.', uk: '✓ Повідомлення надіслано — відповім найближчим часом.', pl: '✓ Wiadomość wysłana — odpowiem wkrótce.' },
    sendingLabel:  { de: 'Wird gesendet…', en: 'Sending…', fr: 'Envoi en cours…', uk: 'Надсилається…', pl: 'Wysyłanie…' },
    sendErr:       { de: 'Fehler — bitte direkt an hello@kkeey.dev mailen', en: 'Error — please email hello@kkeey.dev directly', fr: 'Erreur — écrivez directement à hello@kkeey.dev', uk: 'Помилка — напишіть прямо на hello@kkeey.dev', pl: 'Błąd — prosimy o bezpośredni kontakt na hello@kkeey.dev' },
    darkBtnLight:  { de: 'Hellmodus aktivieren', en: 'Switch to light mode', fr: 'Activer le mode clair', uk: 'Увімкнути світлу тему', pl: 'Włącz tryb jasny' },
    darkBtnDark:   { de: 'Dunkelmodus aktivieren', en: 'Switch to dark mode', fr: 'Activer le mode sombre', uk: 'Увімкнути темну тему', pl: 'Włącz tryb ciemny' },
    footerCross:   { de: 'AI-Engineering-Portfolio ansehen →', en: 'View AI Engineering Portfolio →', fr: 'Découvrir le portfolio IA →', uk: 'Переглянути портфоліо з AI-розробки →', pl: 'Zobacz Portfolio AI Engineering →' },
    downloadNote:  { de: 'Bewerbungsmappe: Anschreiben, Lebenslauf & Tech-Profil (PDF)', en: 'Application portfolio: cover letter, CV & tech profile (PDF)', fr: 'Dossier complet : lettre, CV et profil technique (PDF)', uk: 'Резюме та технічний профіль (PDF)', pl: 'Dokumenty aplikacyjne: list motywacyjny, CV i profil technologiczny (PDF)' },
    systemBadge:   { de: 'ORCHESTRATOR AKTIV', en: 'ORCHESTRATOR ACTIVE', fr: 'ORCHESTRATEUR ACTIF', uk: 'ОРКЕСТРАТОР АКТИВНИЙ', pl: 'ORKIESTRATOR AKTYWNY' },
  },
};
